// Package routegen derives typed API bindings from the dependency-neutral route
// table. Generated Go keeps API implementation types out of authorization code.
package routegen

import (
	"fmt"
	"go/format"
	"go/parser"
	"go/token"
	"sort"
	"strconv"
	"strings"

	"github.com/cavi-ai/secure-agent/daemon/internal/apiroutes"
)

func Generate(routes []apiroutes.Route) ([]byte, error) {
	var body strings.Builder
	imports := map[string]bool{}
	responses := map[string]bool{}
	var types []string
	addType := func(name string) error {
		if name == "" || responses[name] {
			return nil
		}
		if _, err := parser.ParseExpr(name); err != nil {
			return fmt.Errorf("invalid response type %q: %w", name, err)
		}
		responses[name] = true
		for _, part := range strings.FieldsFunc(name, func(r rune) bool {
			return !('a' <= r && r <= 'z' || 'A' <= r && r <= 'Z' || '0' <= r && r <= '9' || r == '_' || r == '.')
		}) {
			if pkg, _, ok := strings.Cut(part, "."); ok && pkg != "api" {
				imports[pkg] = true
			}
		}
		types = append(types, strings.ReplaceAll(name, "api.", ""))
		return nil
	}
	body.WriteString("func (a *API) routes() map[string]http.HandlerFunc {\nreturn map[string]http.HandlerFunc{\n")
	seen := map[string]bool{}
	for _, r := range routes {
		if seen[r.Path] {
			return nil, fmt.Errorf("duplicate route %q", r.Path)
		}
		seen[r.Path] = true
		h := strings.TrimPrefix(r.Handler, "API.")
		if !token.IsIdentifier(h) {
			return nil, fmt.Errorf("invalid handler for %q: %q", r.Path, r.Handler)
		}
		if strings.HasPrefix(r.Handler, "API.") {
			h = "a." + h
		}
		fmt.Fprintf(&body, "%s: %s,\n", strconv.Quote(r.Path), h)
		if err := addType(r.Response); err != nil {
			return nil, err
		}
		for _, leaf := range r.Leaves {
			if err := addType(leaf.Response); err != nil {
				return nil, err
			}
		}
	}
	body.WriteString("}\n}\n")
	for _, r := range routes {
		var leaves []apiroutes.Leaf
		for _, leaf := range r.Leaves {
			if leaf.Handler != "" {
				leaves = append(leaves, leaf)
			}
		}
		if len(leaves) == 0 {
			continue
		}
		name := strings.TrimPrefix(r.Handler, "API.") + "Leaf"
		fmt.Fprintf(&body, "func (a *API) %s(w http.ResponseWriter, r *http.Request, id, leaf string) bool {\nswitch leaf {\n", name)
		seenLeaves := map[string]bool{}
		for _, leaf := range leaves {
			if seenLeaves[leaf.Path] || !token.IsIdentifier(leaf.Handler) {
				return nil, fmt.Errorf("invalid leaf %q on %q", leaf.Path, r.Path)
			}
			seenLeaves[leaf.Path] = true
			fmt.Fprintf(&body, "case %s: a.%s(w, r, id)\n", strconv.Quote(leaf.Path), leaf.Handler)
		}
		body.WriteString("default: return false\n}\nreturn true\n}\n")
	}
	body.WriteString("// RouteWireTypes is derived from response declarations in apiroutes.Table.\nfunc RouteWireTypes() []any { return []any{\n")
	for _, name := range types {
		fmt.Fprintf(&body, "new(%s),\n", name)
	}
	body.WriteString("}\n}\n")
	var src strings.Builder
	src.WriteString("// Code generated by genroutes from apiroutes.Table. DO NOT EDIT.\npackage api\n\nimport (\n\"net/http\"\n")
	var pkgs []string
	for pkg := range imports {
		pkgs = append(pkgs, pkg)
	}
	sort.Strings(pkgs)
	for _, pkg := range pkgs {
		fmt.Fprintf(&src, "%q\n", "github.com/cavi-ai/secure-agent/daemon/internal/"+pkg)
	}
	src.WriteString(")\n")
	src.WriteString(body.String())
	return format.Source([]byte(src.String()))
}
