// Code generated by genroutes from apiroutes.Table. DO NOT EDIT.
package api

import (
	"github.com/cavi-ai/secure-agent/daemon/internal/event"
	"github.com/cavi-ai/secure-agent/daemon/internal/model"
	"github.com/cavi-ai/secure-agent/daemon/internal/resource"
	"github.com/cavi-ai/secure-agent/daemon/internal/store"
	"net/http"
)

func (a *API) routes() map[string]http.HandlerFunc {
	return map[string]http.HandlerFunc{
		"/status":                       a.handleStatus,
		"/sessions":                     a.handleSessions,
		"/sessions/":                    a.handleSessionSubpath,
		"/resources":                    a.handleResources,
		"/resources/episodes":           a.handleResourceEpisodes,
		"/resources/control":            a.handleResourceControl,
		"/resources/policy":             a.handleResourcePolicy,
		"/snapshot":                     a.handleSnapshot,
		"/posture":                      a.handlePosture,
		"/flags":                        a.handleFlags,
		"/reviews":                      a.handleReviews,
		"/reviews/decision":             a.handleReviewDecision,
		"/decision-scopes":              a.handleDecisionScopes,
		"/flags/":                       a.handleFlagExplain,
		"/events":                       a.handleEvents,
		"/events/stream":                a.handleEventStream,
		"/incidents":                    a.handleIncidents,
		"/incidents/status":             a.handleIncidentStatus,
		"/incidents/remediation":        a.handleIncidentRemediation,
		"/audit":                        a.handleAudit,
		"/allowlist/suggestions":        a.handleAllowlistSuggestions,
		"/allowlist":                    a.handleAllowlistAdd,
		"/egress/uninspected":           a.handleUninspectedEgress,
		"/egress/endpoint":              a.handleEndpointDetail,
		"/egress/episodes":              a.handleEgressEpisodes,
		"/egress/episodes/":             a.handleEgressEpisodeSubpath,
		"/expected-egress":              a.handleExpectedEgress,
		"/notify/rules":                 a.handleNotifyRules,
		"/guard/path-allow":             a.handleGuardPathAllow,
		"/mute":                         a.handleMute,
		"/expected":                     a.handleExpected,
		"/advisor/retriage":             a.handleAdvisorRetriage,
		"/advisor/assess-host":          a.handleAdvisorAssessHost,
		"/flags/acknowledge":            a.handleFlagAcknowledge,
		"/patterns":                     a.handlePatterns,
		"/firewall/patterns":            a.handleFirewallPatterns,
		"/guard/config":                 a.handleGuardConfig,
		"/ui/open-fda":                  a.handleOpenFDA,
		"/ui/open-config":               a.handleOpenConfig,
		"/stats/rollup":                 a.handleRollup,
		"/costs":                        a.handleCosts,
		"/costs/unpriced":               a.handleCostsUnpriced,
		"/costs/plans":                  a.handleCostsPlans,
		"/doctor":                       a.handleDoctor,
		"/coverage/probe":               a.handleCoverageProbe,
		"/routing/claude":               a.handleRoutingClaude,
		"/worktrees":                    a.handleWorktrees,
		"/worktrees/repos":              a.handleWorktreeRepos,
		"/worktrees/remove":             a.handleWorktreeRemove,
		"/worktrees/advise":             a.handleWorktreeAdvise,
		"/worktrees/reveal":             a.handleWorktreeReveal,
		"/worktrees/reconnect":          a.handleWorktreeReconnect,
		"/worktrees/trash":              a.handleWorktreeTrash,
		"/worktrees/review-trash":       a.handleWorktreeReviewTrash,
		"/cleanup/ledger":               a.handleCleanupLedger,
		"/worktrees/ask":                a.handleWorktreeAsk,
		"/worktrees/asks":               a.handleWorktreeAsks,
		"/cleanup":                      a.handleCleanup,
		"/cleanup/trash":                a.handleCleanupTrash,
		"/cleanup/clean":                a.handleCleanupClean,
		"/cleanup/advise":               a.handleCleanupAdvise,
		"/advisor/discover":             a.handleAdvisorDiscover,
		"/fleet":                        a.handleFleet,
		"/kill":                         a.handleKill,
		"/firewall/mode":                a.handleFirewallMode,
		"/firewall/fingerprints/reload": a.handleFingerprintReload,
		"/firewall/fingerprints/ingest": a.handleFingerprintIngest,
		"/firewall/sources":             a.handleFirewallSources,
		"/guard/decision":               a.handleGuardDecision,
		"/guard/pending":                a.handleGuardPending,
		"/guard/resolve":                a.handleGuardResolve,
		"/guard/rules":                  a.handleGuardRules,
		"/debug/pprof/":                 handlePprof,
		"/files/detail":                 a.handleFileDetail,
		"/files/reveal":                 a.handleFileReveal,
		"/files/open":                   a.handleFileOpen,
		"/advisor/plan":                 a.handleAdvisorPlan,
		"/labels":                       a.handleLabels,
		"/agent/status":                 a.handleAgentStatus,
		"/agent/skills":                 a.handleAgentSkills,
		"/agent/chat":                   a.handleAgentChat,
		"/agent/analyze":                a.handleAgentAnalyze,
		"/agent/recommendations":        a.handleAgentRecommendations,
		"/agent/worktree":               a.handleAgentWorktree,
		"/agent/actions":                a.handleAgentActions,
		"/agent/plans":                  a.handleAgentPlans,
		"/agent/dispatch":               a.handleAgentDispatch,
		"/agent/runs":                   a.handleAgentRuns,
	}
}
func (a *API) handleSessionSubpathLeaf(w http.ResponseWriter, r *http.Request, id, leaf string) bool {
	switch leaf {
	case "timeline":
		a.serveSessionTimeline(w, r, id)
	case "report":
		a.serveSessionReport(w, r, id)
	case "memory":
		a.serveSessionMemory(w, r, id)
	case "overview":
		a.serveSessionOverview(w, r, id)
	case "outcomes":
		a.serveSessionOutcomes(w, r, id)
	default:
		return false
	}
	return true
}

// RouteWireTypes is derived from response declarations in apiroutes.Table.
func RouteWireTypes() []any {
	return []any{
		new(Status),
		new([]model.Session),
		new([]event.Event),
		new(store.SessionReport),
		new(memoryResponse),
		new(SessionOverview),
		new(SessionOutcomes),
		new(resource.Snapshot),
		new(Snapshot),
		new(Posture),
		new([]model.Flag),
		new(store.ReviewPage),
		new(model.ReviewDecisionReceipt),
		new(model.Flag),
		new([]model.Pattern),
		new(store.CostReport),
		new(DoctorReport),
		new(FleetNodeStatus),
		new(model.FileDetail),
		new(PlanResponse),
	}
}
