// Code generated by wiregen from the Go wire structs. DO NOT EDIT.
// Regenerate: go run ./cmd/genwire (daemon/). Drift fails TestWireTypesDrift.

export interface Event {
  kind: number;
  ts: string;
  pid: number;
  exe_path?: string;
  session_id?: string;
  path?: string;
  remote_host?: string;
  remote_port?: number;
  detail?: string;
  tool?: string;
  tool_status?: string;
  duration_ms?: number;
  model?: string;
  tokens_in?: number;
  tokens_out?: number;
  cost_usd?: number;
  call_id?: string;
}

export interface Session {
  id: string;
  harness: string;
  workspace?: string;
  repo?: string;
  branch?: string;
  root_pid?: number;
  root_started_at?: string;
  parent_id?: string;
  started_at: string;
  ended_at?: string;
  last_seen_at: string;
  status: string;
  confidence: string;
}

export interface EvidenceItem {
  kind: string;
  label: string;
  sub?: string;
  rule?: string;
  ts?: string;
  text?: string;
}

export interface AdvisorVerdict {
  assessment?: string;
  confidence?: number;
  rationale: string;
  suggested_action?: string;
  model?: string;
  created_at: string;
}

export interface ExplainSubject {
  path: string;
  display: string;
  basename: string;
  category: string;
  category_label: string;
  rule?: string;
  owner_label: string;
}

export interface ExplainEgress {
  host: string;
  port?: number;
  org?: string;
  name?: string;
  kind: string;
  allowlisted: boolean;
  gap_seconds: number;
}

export interface ExplainContext {
  session_id?: string;
  harness?: string;
  repo?: string;
  branch?: string;
  workspace?: string;
  tool?: string;
  tool_status?: string;
  tool_at?: string;
  model?: string;
}

export interface Disposition {
  state: string;
  text: string;
  why: string;
}

export interface ExplainAction {
  id: string;
  label: string;
  consequence: string;
  method: string;
  path: string;
  body?: Record<string, unknown>;
  recommended?: boolean;
}

export interface FlagExplain {
  what: string;
  subject?: ExplainSubject;
  egress?: ExplainEgress[];
  context?: ExplainContext;
  disposition: Disposition;
  actions: ExplainAction[];
}

export interface Flag {
  id: string;
  rule: string;
  severity: number;
  ts: string;
  pid: number;
  agent: string;
  session_id?: string;
  workspace?: string;
  evidence: EvidenceItem[];
  title?: string;
  advisor?: AdvisorVerdict;
  acknowledged?: boolean;
  explain?: FlagExplain;
}

export interface RotateItem {
  id: string;
  category: string;
  name: string;
  path?: string;
  risk: string;
  description: string;
  action: string;
}

export interface IncidentReport {
  id: string;
  flag_id: string;
  pid: number;
  agent: string;
  timestamp: string;
  rule: string;
  session_id?: string;
  subject?: string;
  aggregate_count?: number;
  last_flag_at?: string;
  summary: string;
  risk: string;
  touched_files: string[];
  connections: string[];
  rotate_list: RotateItem[];
  advisor_narrative?: string;
}

export interface BudgetStatus {
  mode: string;
  enforced: boolean;
  over_budget: number;
  approval: number;
  contained: number;
  paused: number;
}

export interface NodeStatus {
  hostname: string;
  os: string;
  arch: string;
  agents: number;
  uptime?: string;
  posture_state: string;
  posture_summary: string;
  needs_you: number;
  labels?: Record<string, string>;
  budget?: BudgetStatus;
}

export interface AgentSummary {
  pid: number;
  name: string;
  kind?: string;
  exe_path?: string;
  cwd?: string;
  ppid?: number;
  root_pid?: number;
  started_at?: string;
  last_seen_at?: string;
  rss_bytes?: number;
  cpu_percent?: number;
  is_orphan?: boolean;
  session_id?: string;
  workspace?: string;
  repo?: string;
  branch?: string;
}

export interface AgentTree {
  root: AgentSummary;
  children: AgentSummary[];
  rss_bytes?: number;
  cpu_percent?: number;
  last_seen_at?: string;
}

export interface HealthSnapshot {
  enabled: boolean;
  circuit_open?: boolean;
  last_error?: string;
  queue_depth: number;
  model?: string;
}

export interface CoverageStatus {
  harnesses_active: number;
  harnesses_seen: number;
}

export interface Health {
  name: string;
  running: boolean;
  abandoned: boolean;
  restarts: number;
  last_error?: string;
  last_produced?: string;
}

export interface ESServiceSnapshot {
  state: string;
  spool_size: number;
  spool_mtime: string;
  helper_mtime: string;
}

export interface Status {
  running: boolean;
  version: string;
  uptime: string;
  active_agents: number;
  infra_count?: number;
  agents: AgentSummary[];
  trees: AgentTree[];
  proxy_enabled: boolean;
  proxy_port: number;
  uninspected_egress: number;
  uninspected_infra: number;
  advisor_enabled: boolean;
  advisor_health?: HealthSnapshot;
  tracked_processes: number;
  muted_flags: number;
  fleet_configured?: boolean;
  unacted_flags_24h: number;
  bus_drops?: number;
  coverage?: CoverageStatus;
  firewall_stats?: Record<string, RuleStat>;
  collectors?: Health[];
  es_service?: ESServiceSnapshot;
}

export interface PostureItem {
  kind: string;
  id: string;
  title: string;
  severity: number;
  detail?: string;
  ts?: string;
}

export interface AttentionItem {
  kind: string;
  priority: number;
  id?: string;
  action?: string;
  title: string;
  detail?: string;
  rule?: string;
  path?: string;
  scopeText?: string;
  status?: string;
  count?: number;
  hosts?: string[];
  advisor?: AdvisorVerdict;
  disposition?: Disposition;
}

export interface AttentionGroup {
  key: string;
  label: string;
  agent: string;
  workspace?: string;
  rootPid?: number;
  pids?: number[];
  rssBytes?: number;
  cpuPercent?: number;
  processCount?: number;
  items: AttentionItem[];
}

export interface Posture {
  state: string;
  needs_you: number;
  summary: string;
  items: PostureItem[];
  groups?: AttentionGroup[];
  generated: string;
  connected: boolean;
}

export interface CostRow {
  key: string;
  harness?: string;
  calls: number;
  sessions: number;
  tokens_in: number;
  tokens_out: number;
  cost_usd: number;
  unpriced_calls: number;
}

export interface CostReport {
  since: string;
  until: string;
  by: string;
  total: CostRow;
  rows: CostRow[];
}

export interface DoctorSummary {
  pass: number;
  fail: number;
  skip: number;
}

export interface DoctorCheck {
  id: string;
  title: string;
  state: string;
  detail?: string;
  fix?: string;
}

export interface DoctorReport {
  generated_at: string;
  version: string;
  uptime: string;
  grace: boolean;
  summary: DoctorSummary;
  checks: DoctorCheck[];
}

