// Code generated by wiregen from the Go wire structs. DO NOT EDIT.
// Regenerate: go run ./cmd/genwire (daemon/). Drift fails TestWireTypesDrift.

export interface Event {
  kind: number;
  ts: string;
  pid: number;
  exe_path?: string;
  session_id?: string;
  path?: string;
  remote_host?: string;
  remote_port?: number;
  detail?: string;
  offset?: number;
  tool?: string;
  tool_status?: string;
  duration_ms?: number;
  model?: string;
  provider?: string;
  tokens_in?: number;
  tokens_out?: number;
  cost_usd?: number;
  price_class?: string;
  call_id?: string;
}

export interface Session {
  id: string;
  harness: string;
  workspace?: string;
  repo?: string;
  branch?: string;
  root_pid?: number;
  root_started_at?: string;
  parent_id?: string;
  origin?: string;
  started_at: string;
  ended_at?: string;
  last_seen_at: string;
  status: string;
  confidence: string;
}

export interface EvidenceItem {
  kind: string;
  label: string;
  sub?: string;
  rule?: string;
  ts?: string;
  text?: string;
  offset?: number;
}

export interface AdvisorVerdict {
  assessment?: string;
  confidence?: number;
  rationale: string;
  suggested_action?: string;
  model?: string;
  created_at: string;
}

export interface ExplainSubject {
  path: string;
  display: string;
  basename: string;
  category: string;
  category_label: string;
  rule?: string;
  owner_label: string;
}

export interface ExplainEgress {
  host: string;
  port?: number;
  org?: string;
  name?: string;
  kind: string;
  allowlisted: boolean;
  gap_seconds: number;
}

export interface ExplainContext {
  session_id?: string;
  harness?: string;
  repo?: string;
  branch?: string;
  workspace?: string;
  tool?: string;
  tool_status?: string;
  tool_at?: string;
  model?: string;
}

export interface Disposition {
  state: string;
  text: string;
  why: string;
}

export interface ExplainAction {
  id: string;
  label: string;
  consequence: string;
  method: string;
  path: string;
  body?: Record<string, unknown>;
  recommended?: boolean;
}

export interface LabelSummary {
  ok: number;
  not_ok: number;
}

export interface FlagExplain {
  what: string;
  subject?: ExplainSubject;
  egress?: ExplainEgress[];
  context?: ExplainContext;
  disposition: Disposition;
  actions: ExplainAction[];
  labels?: LabelSummary;
}

export interface Flag {
  id: string;
  rule: string;
  severity: number;
  ts: string;
  pid: number;
  agent: string;
  session_id?: string;
  workspace?: string;
  evidence: EvidenceItem[];
  title?: string;
  advisor?: AdvisorVerdict;
  acknowledged?: boolean;
  explain?: FlagExplain;
}

export interface Pattern {
  key: string;
  agent: string;
  rule: string;
  title: string;
  subject: EvidenceItem;
  count: number;
  unacked: number;
  first: string;
  last: string;
  median_gap_s: number;
  bursts: number;
  cadence: string;
  hourly: number[];
  pids: number[];
  pid_count: number;
  sessions: string[];
  session_count: number;
  disposition: Disposition;
  summary: string;
  actions: ExplainAction[];
  flag_ids: string[];
}

export interface FileFinding {
  kind: string;
  id: string;
  rule: string;
  severity?: number;
  risk?: string;
  ts: string;
  agent?: string;
  session_id?: string;
  acknowledged?: boolean;
  status?: string;
  evidence_kind?: string;
  evidence_rule?: string;
  offset?: number;
}

export interface FileAccess {
  kind: string;
  ts: string;
  pid: number;
  exe_path?: string;
  session_id: string;
}

export interface FileHit {
  flag_id: string;
  rule: string;
  offset?: number;
  ts: string;
}

export interface FileDetail {
  path: string;
  display: string;
  exists: boolean;
  size: number;
  mod_time?: string;
  owned_by_user: boolean;
  subject?: ExplainSubject;
  session?: Session;
  findings: FileFinding[];
  accesses: FileAccess[];
  hits: FileHit[];
  excerpt?: string;
  excerpt_withheld?: string;
}

export interface PlanStep {
  kind: string;
  step: string;
  detail: string;
}

export interface AdvisorPlan {
  summary: string;
  why: string[];
  risk: string;
  prevent: PlanStep[];
  behavior: string[];
  remediate: string[];
  actions: string[];
  confidence: number;
  model?: string;
  created_at: string;
  evidence_key: string;
}

export interface OperatorLabel {
  id: number;
  kind: string;
  rule?: string;
  agent?: string;
  pattern?: string;
  label: string;
  reason?: string;
  source: string;
  created_at: string;
}

export interface LabelSuggestion {
  label: string;
  text: string;
  action_id?: string;
}

export interface LabelContext {
  summary: LabelSummary;
  similar: OperatorLabel[];
  suggestion?: LabelSuggestion;
}

export interface Step {
  kind: string;
  step: string;
  detail: string;
}

export interface Playbook {
  rule: string;
  title: string;
  why: string;
  now: string[];
  prevent: Step[];
  actions: string[];
}

export interface PlanResponse {
  subject: string;
  status: string;
  playbook: Playbook;
  plan?: AdvisorPlan;
  flag?: Flag;
  labels?: LabelContext;
  advisor_ready: boolean;
  reason?: string;
}

export interface RotateItem {
  id: string;
  category: string;
  name: string;
  path?: string;
  risk: string;
  description: string;
  action: string;
}

export interface IncidentReport {
  id: string;
  flag_id: string;
  pid: number;
  agent: string;
  timestamp: string;
  rule: string;
  session_id?: string;
  subject?: string;
  aggregate_count?: number;
  last_flag_at?: string;
  summary: string;
  risk: string;
  touched_files: string[];
  connections: string[];
  rotate_list: RotateItem[];
  advisor_narrative?: string;
}

export interface BudgetStatus {
  mode: string;
  enforced: boolean;
  over_budget: number;
  approval: number;
  contained: number;
  paused: number;
}

export interface NodeStatus {
  hostname: string;
  os: string;
  arch: string;
  agents: number;
  uptime?: string;
  posture_state: string;
  posture_summary: string;
  needs_you: number;
  labels?: Record<string, string>;
  budget?: BudgetStatus;
}

export interface AgentSummary {
  pid: number;
  name: string;
  kind?: string;
  exe_path?: string;
  cwd?: string;
  ppid?: number;
  root_pid?: number;
  started_at?: string;
  last_seen_at?: string;
  rss_bytes?: number;
  cpu_percent?: number;
  is_orphan?: boolean;
  session_id?: string;
  workspace?: string;
  repo?: string;
  branch?: string;
  origin?: string;
}

export interface AgentTree {
  root: AgentSummary;
  children: AgentSummary[];
  rss_bytes?: number;
  cpu_percent?: number;
  last_seen_at?: string;
}

export interface HealthSnapshot {
  enabled: boolean;
  circuit_open?: boolean;
  last_error?: string;
  queue_depth: number;
  model?: string;
}

export interface CoverageStatus {
  harnesses_active: number;
  harnesses_seen: number;
}

export interface Health {
  name: string;
  running: boolean;
  abandoned: boolean;
  restarts: number;
  last_error?: string;
  last_produced?: string;
  source?: string;
  last_poll?: string;
  watermark?: number;
}

export interface ESServiceSnapshot {
  state: string;
  spool_size: number;
  spool_mtime: string;
  helper_mtime: string;
  flooding: boolean;
  unparsed_share: number;
  bytes_skipped: number;
}

export interface Status {
  running: boolean;
  version: string;
  uptime: string;
  active_agents: number;
  infra_count?: number;
  agents: AgentSummary[];
  trees: AgentTree[];
  proxy_enabled: boolean;
  proxy_port: number;
  uninspected_egress: number;
  uninspected_infra: number;
  advisor_enabled: boolean;
  advisor_health?: HealthSnapshot;
  tracked_processes: number;
  muted_flags: number;
  fleet_configured?: boolean;
  unacted_flags_24h: number;
  bus_drops?: number;
  coverage?: CoverageStatus;
  firewall_stats?: Record<string, RuleStat>;
  collectors?: Health[];
  es_service?: ESServiceSnapshot;
}

export interface PostureItem {
  kind: string;
  id: string;
  title: string;
  severity: number;
  detail?: string;
  ts?: string;
}

export interface AttentionItem {
  kind: string;
  priority: number;
  id?: string;
  action?: string;
  title: string;
  detail?: string;
  rule?: string;
  path?: string;
  scopeText?: string;
  status?: string;
  count?: number;
  hosts?: string[];
  advisor?: AdvisorVerdict;
  disposition?: Disposition;
}

export interface AttentionGroup {
  key: string;
  label: string;
  agent: string;
  workspace?: string;
  rootPid?: number;
  pids?: number[];
  rssBytes?: number;
  cpuPercent?: number;
  processCount?: number;
  items: AttentionItem[];
}

export interface Posture {
  state: string;
  needs_you: number;
  summary: string;
  items: PostureItem[];
  groups?: AttentionGroup[];
  generated: string;
  connected: boolean;
}

export interface Machine {
  chip: string;
  ram_bytes: number;
  free_disk_bytes: number;
}

export interface Recommendation {
  id: string;
  label: string;
  source: string;
  endpoint?: string;
  bytes?: number;
  fit: string;
  note: string;
  recommended?: boolean;
  rank: number;
}

export interface DiscoveredServer {
  endpoint: string;
  kind: string;
  models: string[];
  sizes?: Record<string, number>;
}

export interface CostRow {
  key: string;
  harness?: string;
  provider?: string;
  class?: string;
  calls: number;
  sessions: number;
  tokens_in: number;
  tokens_out: number;
  cost_usd: number;
  unpriced_calls: number;
  unknown_model_calls: number;
  unpriced_model_calls: number;
  plan_calls: number;
  local_calls: number;
}

export interface CostReport {
  since: string;
  until: string;
  by: string;
  total: CostRow;
  rows: CostRow[];
  generated_at?: string;
  refreshing?: boolean;
}

export interface PlanWindow {
  window_minutes: number;
  used_percent: number;
  resets_at: string;
}

export interface PlanSnapshot {
  harness: string;
  home: string;
  home_path: string;
  plan_type: string;
  limit_id: string;
  windows: PlanWindow[];
  unlimited: boolean;
  seen_at: string;
}

export interface ReportCount {
  key: string;
  count: number;
  errors?: number;
  duration_ms?: number;
}

export interface ReportModel {
  model: string;
  calls: number;
  tokens_in: number;
  tokens_out: number;
  cost_usd: number;
  unpriced_calls: number;
}

export interface ReportLine {
  ts: string;
  kind: string;
  label: string;
  status?: string;
  duration_ms?: number;
}

export interface SessionReport {
  session: Session;
  duration_s: number;
  events: number;
  turns: number;
  tool_calls: number;
  model_calls: number;
  tokens_in: number;
  tokens_out: number;
  cost_usd: number;
  unpriced_calls: number;
  tools: ReportCount[];
  models: ReportModel[];
  files: ReportCount[];
  hosts: ReportCount[];
  guard: ReportLine[];
  secret_hits: ReportLine[];
  flags: Flag[];
  timeline: ReportLine[];
}

export interface DoctorSummary {
  pass: number;
  fail: number;
  skip: number;
}

export interface DoctorCheck {
  id: string;
  title: string;
  state: string;
  detail?: string;
  fix?: string;
}

export interface DoctorReport {
  generated_at: string;
  version: string;
  uptime: string;
  grace: boolean;
  summary: DoctorSummary;
  checks: DoctorCheck[];
}

export interface EndpointIdentity {
  org?: string;
  name?: string;
  kind: string;
  ip?: string;
  class?: string;
}

export interface UninspectedEndpoint {
  agent: string;
  host: string;
  count: number;
  first_seen?: string;
  last_seen: string;
  session_id?: string;
  infra?: string;
  identity: EndpointIdentity;
  assessment?: string;
  rationale?: string;
}

export interface EndpointAllowance {
  agent: string;
  host: string;
}

export interface EndpointDetail {
  host: string;
  identity: EndpointIdentity;
  agents: string[];
  sessions: Session[];
  count: number;
  first_seen?: string;
  last_seen?: string;
  infra?: string;
  allowed?: EndpointAllowance[];
  events: Event[];
}

export interface Suggestion {
  agent: string;
  host: string;
  count: number;
  identity: EndpointIdentity;
  assessment?: string;
  rationale?: string;
  confidence?: number;
}

export interface MutePair {
  rule: string;
  host: string;
  agent?: string;
  title?: string;
}

export interface ScanSummary {
  repos: number;
  worktrees: number;
  remove: number;
  review: number;
  keep: number;
  prune: number;
  stale: number;
  size_bytes: number;
  removable_bytes: number;
}

export interface Worktree {
  path: string;
  branch?: string;
  head?: string;
  detached?: boolean;
  locked?: boolean;
  lock_reason?: string;
  orphan?: boolean;
  reconnect?: string;
  state: string;
  reasons: string[];
  stale?: boolean;
  last_activity?: string;
  idle_days: number;
  in_use?: boolean;
  upstream?: string;
  ahead?: number;
  behind?: number;
  upstream_gone?: boolean;
  changed?: number;
  untracked?: number;
  conflicts?: number;
  paths?: string[];
  unique_commits?: number;
  loose_commits?: number;
  merged?: string;
  size_bytes?: number;
  size_partial?: boolean;
  submodules?: number;
  submodule_local?: string[];
  stashes?: number;
  precious_ignored?: string[];
  other_ignored?: number;
  error?: string;
}

export interface RepoReport {
  path: string;
  source?: string;
  default_branch?: string;
  bare?: boolean;
  size_bytes: number;
  worktrees: Worktree[];
  error?: string;
}

export interface Volume {
  mount: string;
  total_bytes: number;
  free_bytes: number;
}

export interface CleanupTotals {
  trashed_bytes: number;
  trashed_count: number;
  bytes: number;
  count: number;
  bytes_30d: number;
  count_30d: number;
}

export interface ScanReport {
  generated_at: string;
  duration_ms: number;
  cached: boolean;
  stale_days: number;
  summary: ScanSummary;
  repos: RepoReport[];
  errors?: string[];
  sizing?: boolean;
  refreshing?: boolean;
  removals?: Record<string, Removal>;
  volumes?: Volume[];
  reclaimed?: CleanupTotals;
  asks?: Record<string, AgentAsk>;
  advice?: Record<string, AdvisorVerdict>;
}

export interface Removal {
  path: string;
  state: string;
  phase?: string;
  step?: string;
  step_at?: string;
  error?: string;
  row_state?: string;
  reasons?: string[];
  branch?: string;
  bytes?: number;
  files?: number;
  started_at: string;
  finished_at?: string;
}

export interface ClutterItem {
  id: string;
  kind: string;
  name: string;
  path: string;
  project?: string;
  worktree?: string;
  size_bytes?: number;
  files?: number;
  size_partial?: boolean;
  last_touched?: string;
  idle_days: number;
  action: string;
  command?: string;
  note?: string;
}

export interface ClutterKindTotal {
  kind: string;
  bytes: number;
  count: number;
}

export interface ClutterProjectTotal {
  project: string;
  bytes: number;
  count: number;
}

export interface ClutterReport {
  generated_at: string;
  sizing?: boolean;
  refreshing?: boolean;
  items: ClutterItem[];
  kinds: ClutterKindTotal[];
  projects: ClutterProjectTotal[];
  volumes?: Volume[];
  reclaimed?: CleanupTotals;
  advice?: Record<string, AdvisorVerdict>;
}

export interface ClutterResult {
  item: ClutterItem;
  bytes: number;
  bytes_partial?: boolean;
  trash_path?: string;
  output?: string;
}

export interface CleanupEntry {
  id: number;
  ts: string;
  action: string;
  path: string;
  repo?: string;
  bytes: number;
  detail?: string;
}

export interface CleanupDay {
  day: string;
  bytes: number;
  count: number;
  trashed_bytes: number;
  trashed_count: number;
}

export interface AgentAsk {
  id: number;
  ts: string;
  path: string;
  repo?: string;
  harness: string;
  session_id: string;
  status: string;
  verdict?: string;
  detail?: string;
  cost_usd?: number;
  output?: string;
  finished_at?: string;
}

