// Package wiregen generates TypeScript types from the Go wire structs so the
// console's view of the API can never silently drift from the daemon.
// wire-types.d.ts is committed; TestWireTypesDrift regenerates and compares,
// so a Go-side shape change fails CI until the .d.ts is regenerated.
package wiregen

import (
	"fmt"
	"reflect"
	"sort"
	"strings"
	"time"

	"github.com/cavi-ai/secure-agent/daemon/internal/advisor"
	"github.com/cavi-ai/secure-agent/daemon/internal/api"
	"github.com/cavi-ai/secure-agent/daemon/internal/event"
	"github.com/cavi-ai/secure-agent/daemon/internal/model"
	"github.com/cavi-ai/secure-agent/daemon/internal/store"
	"github.com/cavi-ai/secure-agent/daemon/internal/supervise"
)

// WireTypes is the single list of structs that cross the daemon's API
// boundary into clients. Adding a field anywhere here changes the generated
// file — the drift test fails until it's regenerated.
func WireTypes() []any {
	return []any{
		event.Event{},
		model.Session{},
		model.Flag{},
		model.IncidentReport{},
		model.RotateItem{},
		model.AdvisorVerdict{},
		model.NodeStatus{},
		api.Status{},
		api.AgentSummary{},
		api.CoverageStatus{},
		api.Posture{},
		api.PostureItem{},
		api.AttentionGroup{},
		api.AttentionItem{},
		supervise.Health{},
		advisor.HealthSnapshot{},
		store.CostRow{},
		store.CostReport{},
		store.SessionReport{},
		store.ReportCount{},
		store.ReportModel{},
		store.ReportLine{},
		api.DoctorReport{},
		api.DoctorCheck{},
	}
}

// Generate renders the .d.ts for the full wire-type set.
func Generate() string { return TypeScript(WireTypes()...) }

var timeType = reflect.TypeOf(time.Time{})

// TypeScript renders the given types as .d.ts interfaces. json tags drive
// names; omitempty becomes optional. Nested structs are emitted too.
func TypeScript(types ...any) string {
	emitted := map[string]bool{}
	var out strings.Builder
	out.WriteString("// Code generated by wiregen from the Go wire structs. DO NOT EDIT.\n")
	out.WriteString("// Regenerate: go run ./cmd/genwire (daemon/). Drift fails TestWireTypesDrift.\n\n")
	for _, t := range types {
		emitTS(reflect.TypeOf(t), &out, emitted)
	}
	return out.String()
}

func emitTS(t reflect.Type, out *strings.Builder, emitted map[string]bool) {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	if t.Kind() != reflect.Struct || t == timeType || emitted[t.Name()] {
		return
	}
	emitted[t.Name()] = true
	// Emit referenced structs first (fields reference their names).
	for i := 0; i < t.NumField(); i++ {
		ft := t.Field(i).Type
		for ft.Kind() == reflect.Pointer || ft.Kind() == reflect.Slice {
			ft = ft.Elem()
		}
		emitTS(ft, out, emitted)
	}
	fmt.Fprintf(out, "export interface %s {\n", t.Name())
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		tag := f.Tag.Get("json")
		if tag == "-" {
			continue
		}
		name, opts, _ := strings.Cut(tag, ",")
		if name == "" {
			name = f.Name
		}
		optional := strings.Contains(opts, "omitempty")
		tsType := tsTypeOf(f.Type)
		opt := ""
		if optional {
			opt = "?"
		}
		fmt.Fprintf(out, "  %s%s: %s;\n", name, opt, tsType)
	}
	out.WriteString("}\n\n")
}

func tsTypeOf(t reflect.Type) string {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int32, reflect.Int64, reflect.Float64, reflect.Uint64, reflect.Int16, reflect.Uint32:
		return "number"
	case reflect.Slice:
		return tsTypeOf(t.Elem()) + "[]"
	case reflect.Map:
		return "Record<string, " + tsTypeOf(t.Elem()) + ">"
	case reflect.Struct:
		if t == timeType {
			return "string" // RFC3339
		}
		return t.Name()
	case reflect.Interface:
		return "unknown"
	default:
		return "unknown"
	}
}

// Names returns the sorted set of emitted type names (test hook).
func Names(ts string) []string {
	var out []string
	for _, line := range strings.Split(ts, "\n") {
		if strings.HasPrefix(line, "export interface ") {
			out = append(out, strings.TrimSuffix(strings.TrimPrefix(line, "export interface "), " {"))
		}
	}
	sort.Strings(out)
	return out
}

// JSONKeys returns every JSON key a struct (or its nested structs) emits,
// with nested keys flattened one level (e.g. "advisor.assessment"). The
// Swift mirror drift test uses this to prove the hand-written Codable types
// declare everything the daemon can send.
func JSONKeys(v any) []string {
	seen := map[string]bool{}
	var walk func(t reflect.Type, prefix string, depth int)
	walk = func(t reflect.Type, prefix string, depth int) {
		for t.Kind() == reflect.Pointer || t.Kind() == reflect.Slice {
			t = t.Elem()
		}
		if t.Kind() != reflect.Struct || t == timeType || depth > 2 {
			return
		}
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			tag := f.Tag.Get("json")
			if tag == "-" {
				continue
			}
			name, _, _ := strings.Cut(tag, ",")
			if name == "" {
				name = f.Name
			}
			ft := f.Type
			for ft.Kind() == reflect.Pointer || ft.Kind() == reflect.Slice {
				ft = ft.Elem()
			}
			if ft.Kind() == reflect.Struct && ft != timeType && depth < 2 {
				// Nested object: recurse (keys are what the Swift side must
				// declare as a sub-struct; the parent key covers the leaf).
				walk(ft, prefix+name+".", depth+1)
			}
			seen[prefix+name] = true
		}
	}
	walk(reflect.TypeOf(v), "", 0)
	out := make([]string, 0, len(seen))
	for k := range seen {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
